version: '2'
services:
  redis:
    image: redis
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: stockallj/microservices-docker-django:latest
    container_name: cinema-ui
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      - redis
    extra_hosts:
      - "movies.dev:10.10.11.106"
      - "bookings.dev:10.10.11.106"
      - "users.dev:10.10.11.106"
      - "showtimes.dev:10.10.11.106"
