version: '2'
services:
  redis:
    image: redis
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: stockallj/cinema-ui
    container_name: cinema-ui
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      DOMAIN_SUFFIX: .dev
    extra_hosts:
      # Set these to your docker host
      - "movies.dev:172.20.0.1"
      - "bookings.dev:172.20.0.1"
      - "users.dev:172.20.0.1"
      - "showtimes.dev:172.20.0.1"
