apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: cinema
spec:
  rules:
  - host: cinema.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: cinema
  labels:
    app: ui
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: ui
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cinema
  labels:
    app: ui
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: cinema
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: stockallj/cinema-ui
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 0.2
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 200m
