apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: cinema
  labels:
    app: ui
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: ui
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cinema
  labels:
    app: ui
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: stockallj/cinema-ui
          ports:
            - containerPort: 80
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
